### ISSUE TITLE
VERSIONDATE does not get replaced in tikz-trackschematic.sty

### ISSUE THREAD

**Issue by apriljunge** [railtoolkit/tikz-trackschematic#16]
In all bash scripts (except create-release.sh) the replacement of VERSIONDATE is missing.
This breaks the scripts.

https://github.com/railtoolkit/tikz-trackschematic/blob/6dc00facc4d11a92a4761d214c6d7be1cf9fec5e/src/tikz-trackschematic.sty#L8

**Comment by kaat0** [comment]
It is probably about line 194 in the shell script, but I can't understand your error at the moment: can you please provide more context? In particular, which "sed" version do you have, which OS are you using?
What does "sed --version" return?

sed is actually a bit problematic because there are many implementations. I have only tested it on Ubuntu in github actions and on a BSD. Have a look at lines 42 to 45 in the shell script as well.

**Comment by apriljunge** [comment]
When I execute pdflatex I get this error:

```
(/usr/local/share/texmf/tex/latex/local/tikz-trackschematic-dev/tikzlibrarytrackschematic-dev.code.tex)
! Missing = inserted for \ifnum.
<to be read again> 
                   V
l.9
```

I can solve this by removing `[VERSIONDATE tikz-trackschematic]` completely or replacing `VERSIONDATE` it with a valid date.
This issue is discussed here: https://tex.stackexchange.com/questions/274650/missing-inserted-for-ifnum

**Comment by kaat0** [comment]
Fixed issue with https://github.com/railtoolkit/tikz-trackschematic/commit/83a0a6f2ec573d53064c93ff1a5dd431155738af
